In [1]:
import numpy as np

In [2]:
#create a 1 dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
#Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)
print(type(arr1))

(5,)
1
int64
5
<class 'numpy.ndarray'>


In [7]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(type(arr2))

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


In [9]:
df = pd.DataFrame(arr2)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [11]:
ones = np.ones((10,2))

In [12]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
zeros = np.zeros((7,2,3))

In [14]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
arr = np.arange(0,101,3)

In [16]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
rand1 = np.random.randint(0,10,size=(7,2))

In [20]:
rand1

array([[2, 6],
       [1, 8],
       [7, 3],
       [7, 4],
       [3, 8],
       [2, 6],
       [6, 2]], dtype=int32)

In [21]:
rand2 = np.random.random((3,5))

In [22]:
rand2

array([[0.01245844, 0.77492259, 0.66626143, 0.60750944, 0.34112709],
       [0.58754596, 0.71948484, 0.13272   , 0.3552524 , 0.70912628],
       [0.76334479, 0.90689989, 0.50521281, 0.69305602, 0.79859385]])

In [23]:
np.random.seed(42)

rand3 = np.random.randint(0,10,size=(4,6))

In [24]:
rand3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [25]:
rand4 = np.random.randint(1,11,size=(3,7))

np.unique(rand4)

array([ 1,  2,  3,  4,  5,  7,  9, 10], dtype=int32)